version: '3'
services:
  server:
    build:
      context: api
      dockerfile: ../Dockerfile
    volumes:
      - ./api:/src
      - /src/node_modules
    working_dir: /src
    ports:
      - 127.0.0.1:3001:3001

  client:
    build:
      context: client
      dockerfile: ../Dockerfile
    volumes:
      - ./client:/src
      - /src/node_modules
    working_dir: /src
    ports:
      - 127.0.0.1:3000:3000
